"""Combine all 35 chapter outlines into one master BOOK-OUTLINE.md.

Reads control/chapter-registry.md for the chapter order (by slug), then
concatenates outlines/<slug>.md in that order under part headings.

    python tools/build_book_outline.py

Output: outlines/BOOK-OUTLINE.md  (regenerate any time; it is a build artifact)
"""
import re
import pathlib
from datetime import date

BASE = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = BASE / "control" / "chapter-registry.md"
OUTDIR = BASE / "outlines"
OUTFILE = OUTDIR / "BOOK-OUTLINE.md"

PARTS = {
    "1": "Part 1 — The Land and Its First Peoples",
    "2": "Part 2 — Coming, Moving, Settling",
    "3": "Part 3 — Making and Building",
    "4": "Part 4 — Work, Food, and Money",
    "5": "Part 5 — Power, Law, and War",
    "6": "Part 6 — Freedom and Fairness",
    "7": "Part 7 — Health and Safety",
    "8": "Part 8 — Faith, Learning, and News",
    "9": "Part 9 — Culture and Play",
}

HEADER = f"""<!-- hb-note -->
# A History of the United States — Master Book Outline

*Generated {date.today().isoformat()} by `tools/build_book_outline.py`. Do not edit this file directly —
edit the per-chapter outlines in `outlines/<slug>.md` and rebuild.*

## What this book is

**A grid.** Every chapter is one subject — one angle, one lens on American history — and every chapter
runs through the same ten time sections, from before 1500 to today.

**The finished product is something you scroll through.** You scroll **down through time**, watching one
subject change across five centuries. You slide **left and right through the angles** — the perspectives,
the lenses — to see what every other subject was doing at that same moment in history. Stand anywhere in
the grid and you can look one way to see a subject's whole life, or the other way to see a whole moment.

Each time section is built in three zooms: it opens **wide** on the whole era, moves **closer** to shorter
spans inside it, and then comes all the way in to **individual true stories** about real people. Nothing in
this book is invented — every fact, person, and story comes from research, and where the sources disagree,
the book says so.

Where a subject genuinely has nothing to tell in an era, the book says that plainly rather than padding.

## The ten time sections

Before 1500 · The 1500s · The 1600s · 1700 to 1750 · 1750 to 1800 · 1800 to 1850 · 1850 to 1900 ·
1900 to 1950 · 1950 to 2000 · 2000 to Today
<!-- /hb-note -->

"""


def registry_rows():
    """Yield (num, slug, title, part) from the registry table, in order."""
    text = REGISTRY.read_text(encoding="utf-8")
    row = re.compile(r"^\|\s*(\d{2})\s*\|\s*`([a-z0-9-]+)`\s*\|\s*([^|]+?)\s*\|\s*(\d)\s*\|", re.M)
    for m in row.finditer(text):
        yield m.group(1), m.group(2), m.group(3), m.group(4)


def main():
    chapters = list(registry_rows())
    if not chapters:
        raise SystemExit("No chapters parsed from the registry — check its table format.")

    out, toc, missing, current_part = [HEADER], ["## Contents\n"], [], None

    for num, slug, title, part in chapters:
        if part != current_part:
            toc.append(f"\n**{PARTS.get(part, 'Part ' + part)}**\n")
            current_part = part
        toc.append(f"- {num}. [{title}](#chapter-{num}-{slug})\n")

    out.append("<!-- hb-note -->\n" + "".join(toc) + "<!-- /hb-note -->\n")

    current_part = None
    for num, slug, title, part in chapters:
        path = OUTDIR / f"{slug}.md"
        if part != current_part:
            out.append(f"\n\n<!-- hb-note -->\n# {PARTS.get(part, 'Part ' + part)}\n<!-- /hb-note -->\n")
            current_part = part
        # bare anchor line: the grid parser ignores non-marker lines outside blocks
        out.append(f'\n\n<a id="chapter-{num}-{slug}"></a>\n\n')
        if not path.exists():
            out.append(f"# Chapter {num}: {title}\n\n*(outline file missing: {slug}.md)*\n")
            missing.append(slug)
            continue
        body = path.read_text(encoding="utf-8").strip()
        out.append(body + "\n\n---\n")

    OUTFILE.write_text("".join(out), encoding="utf-8", newline="")
    words = len(OUTFILE.read_text(encoding="utf-8").split())
    print(f"Built {OUTFILE.relative_to(BASE)} — {len(chapters)} chapters, {words:,} words")
    if missing:
        print("MISSING outline files: " + ", ".join(missing))


if __name__ == "__main__":
    main()
